### ISSUE TITLE
TestReap_ReapChildren fails randomly on x86_32 (unreliable test?)

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/go-reap#5]
`TestReap_ReapChildren` usually fails on _i686_ as follows:

```
--- FAIL: TestReap_ReapChildren (1.00s) 
        reap_unix_test.go:53: should have reaped 18206 
```

**Comment by onlyjob** [comment]
ping?

**Comment by tpot** [comment]
I'm pretty sure this is a race between the goroutine that calls ReapChildren() and hitting the select statement that pulls off the pids channel.  I added a sleep after the goroutine to give it time to get started and the test hasn't failed in over an hour.  

There's probably a nicer way to synchronise this though.

[reap_unix_test_patch.txt](https://github.com/hashicorp/go-reap/files/448684/reap_unix_test_patch.txt)

**Comment by slackpad** [comment]
Thanks @tpot I went ahead and took your patch via https://github.com/hashicorp/go-reap/commit/04ce4d0638f3b39b8a8030e2a22c4c90771fa5d6. This test is a bit flaky because it does have some timeouts, so hopefully this will be good enough. If it continues to fail randomly we can look into a better synchronization mechanism.

**Comment by tpot** [comment]
Thanks @slackpad!
